export const mockJobs = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp Inc.",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$120k - $150k",
    category: "Engineering",
    postedDate: "2 days ago",
    logo: "https://images.unsplash.com/photo-1549924231-f129b911e442?w=100&h=100&fit=crop&crop=center",
  },
  {
    id:"2",
    title: "UX Designer",
    company: "Design Studio",
    location: "New York, NY",
    type: "Contract",
    salary: "$80k - $100k",
    category: "Design",
    postedDate: "1 week ago",
    logo: "https://images.unsplash.com/photo-1558403194-611308249627?w=100&h=100&fit=crop&crop=center",
  },
  {
    id: "3",
    title: "Product Manager",
    company: "StartupXYZ",
    location: "Remote",
    type: "Full-time",
    salary: "$90k - $130k",
    category: "Product",
    postedDate: "3 days ago",
    logo: "https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=100&h=100&fit=crop&crop=center",
  },
  {
    id: "4",
    title: "Data Scientist",
    company: "AI Solutions",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$110k - $140k",
    category: "Data Science",
    postedDate: "5 days ago",
    logo: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=100&h=100&fit=crop&crop=center",
  },
  {
    id: "5",
    title: "Marketing Specialist",
    company: "Growth Co.",
    location: "Chicago, IL",
    type: "Part-time",
    salary: "$50k - $70k",
    category: "Marketing",
    postedDate: "1 day ago",
    logo: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=100&h=100&fit=crop&crop=center",
  },
  {
    id:"6",
    title: "DevOps Engineer",
    company: "CloudFirst",
    location: "Seattle, WA",
    type: "Full-time",
    salary: "$100k - $135k",
    category: "Engineering",
    postedDate: "4 days ago",
    logo: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=100&h=100&fit=crop&crop=center",
  },
];
