import type { Metadata } from "next";
import {Poppins } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/Providers/NextAuthSessionProvider";
import { Toaster } from "react-hot-toast";

// Configure Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "HireHub",
  description: "Generated by Farhana Sharna",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <NextAuthSessionProvider>
      <body
        className={`${poppins.className} antialiased`}
      >
        <Toaster/>
        {children}
      </body>
      </NextAuthSessionProvider>
    </html>
  );
}
